### ISSUE TITLE
Ability to store directory keys only

### ISSUE THREAD

**Issue by vector-man** [jchristn/WatsonDedupe#2]
I need to store a list of directory paths, along with files. Is there a way to only add a path to the database?

**Comment by jchristn** [comment]
There is not.  The library assumes it's going to index and store the underlying chunks from the data (that way each chunk is stored in a single-instance manner).  

Is your use case one where you need to maintain a list of unique paths?

**Comment by vector-man** [comment]
I'm looking to store unique directory paths (I guess just keys and nothing else) in the database.

I also need in some cases, to only store the path (key) and hash of a file, instead of the file data too.

I need this, because I'm trying to create a snapshot of a directory structure and all files, but I don't need to store the actual data sometimes, just a "signature" to verify a directories' contents and structure haven't changed.

I guess I could store this data in a separate JSON or database file or something, but I was trying to simplify my design by just using one database.

**Comment by jchristn** [comment]
Got it. Not sure this project would be right for that use case, but I do have a lightweight ORM for SQLite that may make life easier for you: https://github.com/jchristn/WatsonORM

Let me know if you want to give it a go and how I can help
